pipeline {
    agent any
    
    tools {
        maven 'Maven 3.5.4'
        jdk 'jdk8'
    }
    
    stages {
        
    	stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage ('Build') {
            steps {
                sh 'mvn -f demo/pom.xml -Dmaven.test.skip=true clean package'
            }
        }
        
        stage ('Deploy') {
            steps {
                sh 'sshpass -p tomcat scp /var/jenkins_home/workspace/myPileline/demo/target/*.war root@47246e25e88d:/usr/local/tomcat/webapps'
            }
        }
	}
}